# Site settings
title: Sh*t You Should Know
header-img: img/home-bg.jpg
email: acmotanya@gmail.com
description: "We stir the pot on all issues; political and entertainment alike."
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://yourdomain.com"
twitter_username: acebom
facebook_username:  aceboogie

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]


#Default settings
